services:
  db:
    image: postgres
    container_name: pg
    tty: true
    env_file:
      - .env
    restart: on-failure
    networks:
      - postgres
    ports:
      - 3333:5432
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "16686:16686"
    healthcheck:
      test: [ "CMD", "curl", "-X", "GET", "localhost:14268/health" ]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s

networks:
  postgres:
    driver: bridge